chapter 03 (Saeid´s Homework)
SmartAcademyVienna/JavaScript_course pull request #19
Opened 2019-05-11 12:00 UTC by saeidnavaser

Hi Ahmad can you see if this pull request is correct or not...

2019-05-12 09:35 UTC, AhmedBHameed requested changes

2019-05-12 09:35 UTC, AhmedBHameed commented on .idea/JavaScript_course.iml
> +<?xml version="1.0" encoding="UTF-8"?>
What is that file !!!

2019-05-12 09:35 UTC, AhmedBHameed commented on HOMEWORKS/Chapter_03/Saeid/Homework_01/assets/js/script.js
> +};
Please do not use `getter` and `setter`. I know it is right but nothing from what we already taken!

2019-05-12 09:35 UTC, AhmedBHameed commented on HOMEWORKS/Chapter_03/Saeid/Homework_02/assets/js/script.js
> +// We send new price value
No accepted this amount of JS coding. Try to make your thoughts out of the box.

2019-05-12 09:35 UTC, AhmedBHameed commented on HOMEWORKS/Chapter_03/Saeid/Homework_02/index.html
> +<!DOCTYPE html>
Focusing on showing data on HTML leading to static pages. We are learning JS to make dynamic pages.

2019-05-24 00:52 UTC, closed without merging

2019-05-24 00:54 UTC, saeidnavaser commented
I close that pull request  and send new